### ISSUE TITLE
Support for OrchardCore 1.7.1

### ISSUE THREAD

**Issue by DotCat1985** [EtchUK/Etch.OrchardCore.SEO#100]
Could you upgrade SEO module for [OrchardCore 1.7.1](https://github.com/OrchardCMS/OrchardCore/releases/tag/v1.7.1)?

**Comment by ColinRaaijmakers** [comment]
+1

**Comment by DotCat1985** [comment]
Could I have any feedback? Thank you.

**Comment by peterkeating** [comment]
New version available that targets 1.7.2.

https://www.nuget.org/packages/Etch.OrchardCore.SEO/1.7.0
