### ISSUE TITLE
Improve wording on Hostname redirects

### ISSUE THREAD

**Issue by mobinzk** [EtchUK/Etch.OrchardCore.SEO#2]
The suggestion is to make the options more obvious, with better wording related to how it would improve the SEO or why it should be done for SEO improvements.

One improvement example could be, instead of having different options for redirect such as Redirect to WWW, Redirect to none WWW and etc. we'll have:
Set your main domain:
- Any domain
- https://www.example.com
- https://example.com
- Custom

**Comment by lawrencedine** [comment]
I'd also suggest making the hint on the `Ignored Urls` a bit clearer too having just gone to look up the code to figure out if it was exact URLs or `StartsWith`. (It's `StartsWith`)
