### ISSUE TITLE
Media field issue with white space character on the filename

### ISSUE THREAD

**Issue by mobinzk** [EtchUK/Etch.OrchardCore.SEO#21]
I've done more debug on this and the issue is with Hostname redirects module. Disabling this module solves the issue.

> There seems to be an issue with MediaField for when selecting an image that has white space on the filename. e.g. Profile/profile 1.png.
> Selecting the image is fine and can successfully save the content item but after going back to edit the content item, the image doesn't get display and instead I get Not Found, It will be discarded on saving.
> 
> I've debugged this and found when js tries to get the image detail from /OrchardCore.Media/Admin/GetMediaItem?path= fails with error saying redirected you too many times. .

More info: https://github.com/OrchardCMS/OrchardCore/issues/4013

**Comment by peterkeating** [comment]
@mobinzk Is there a specific configuration that makes this occur? Just looking at this for another project and doesn't seem to be an issue...

**Comment by peterkeating** [comment]
Got the issue when looking at images within the media library.

**Comment by peterkeating** [comment]
Think ignoring any admin related URLs would be a sensible default as per https://github.com/EtchUK/Etch.OrchardCore.SEO/issues/20.
