### ISSUE TITLE
Hostname Redirects: Admin routes which do not contain admin still redirect

### ISSUE THREAD

**Issue by lawrencedine** [EtchUK/Etch.OrchardCore.SEO#25]
Per the title #24 addresses the literal issue from #20 but it doesn't consider modules which do not use the `admin` path segment (e.g. templates, deployment plans). Unfortunately the `RewriteOptionsService` is executed before any MVC code has had a chance to execute so we do not yet know which controllers are in use so cannot check for their `AdminAttribute` or `Admin` prefix.

Still there may be some way around this.

**Comment by peterkeating** [comment]
I've been unable to find a way around this, was hoping to use a filter but unfortunately the request has been processed too far.

Closing for now.
