### ISSUE TITLE
Meta Tags should use a MediaField

### ISSUE THREAD

**Issue by lawrencedine** [EtchUK/Etch.OrchardCore.SEO#30]
Ideally the `MetaTagsPart` should be using a `MediaField` directly. This would prevent issues like #28 from happening.

Consideration would have to be given for the migration process from storing the image URLs on the part directly and it would probably be a good idea to maintain that property as a facade over the new Field to keep existing projects happy.

**Comment by peterkeating** [comment]
Another example why we should be using fields for this - https://github.com/EtchUK/Etch.OrchardCore.SEO/issues/41
