### ISSUE TITLE
No MetaTags UI when editing content items

### ISSUE THREAD

**Issue by devlife** [EtchUK/Etch.OrchardCore.SEO#36]
I just enabled MetaTags and added the content part to a content definition. However, when I edit the content item I don't see the metatags UI. Am I missing something?

**Comment by lawrencedine** [comment]
@devlife Since version `0.5.1` of this module the `MetaTags` feature uses editor tabs in Orchard Core, can you see this tab as pictured below?

![image](https://user-images.githubusercontent.com/925349/69792044-af8d8500-11bd-11ea-84bc-216b98a16e5d.png)
