### ISSUE TITLE
Unable to add redirect from homepage

### ISSUE THREAD

**Issue by peterkeating** [EtchUK/Etch.OrchardCore.SEO#5]
When enabling the 301 redirects module, the user isn't able to add a redirect from the homepage to another URL. When entering "/" and saving a redirect, the save is successful, however the from URL field value is empty and the redirect doesn't kick in.

**Comment by DannyT** [comment]
Also unable to redirect *to* the homepage (e.g. redirect from /dan to /)

**Comment by peterkeating** [comment]
This has been resolved by @mobinzk - https://github.com/EtchUK/Etch.OrchardCore.SEO/pull/35
