### ISSUE TITLE
Update Orchard nugets 

### ISSUE THREAD

**Issue by MikeKry** [EtchUK/Etch.OrchardCore.SEO#50]
After enabling routing feature, orchard throws following error:

TypeLoadException: Could not load type 'OrchardCore.ContentManagement.Routing.AutorouteEntry' from assembly 'Etch.OrchardCore.SEO, Version=0.5.5.0, Culture=neutral, PublicKeyToken=null' due to value type mismatch.

Etch.OrchardCore.SEO.Redirects.Startup.Configure(IApplicationBuilder app, IEndpointRouteBuilder routes, IServiceProvider serviceProvider)

I have newest orchard nugets, so I believe that is the root cause. There is change in AutorouteEntry constuctor, so it needs to be changed from `new AutorouteEntry { ContentItemId = contentItemId, Path = path }` to  `new AutorouteEntry(contentItemId, path)`

I will submit PR later..

**Comment by peterkeating** [comment]
Likely an API change within Orchard Core or ASP.NET Core MVC when an upgrade occurs. We tend to wait for a new stable releases of Orchard Core before updating the code base. Think we'll be doing that pretty soon though as RC2 is right around the corner. 

You'll see we've done a little bit of preparation for the next stable release on the `upgrade/rc2` branch - https://github.com/EtchUK/Etch.OrchardCore.SEO/commit/a4fb352359ab29947f88d1010cb345f2244ea738.

**Comment by MikeKry** [comment]
@peterkeating 

Cool, thanks for response, pretty much same as I have done for my project, so I will just wait and replace project with nuget as soon as possible.
