### ISSUE TITLE
Sitemaps error with enabled redirects

### ISSUE THREAD

**Issue by MikeKry** [EtchUK/Etch.OrchardCore.SEO#51]
Sitemap breaks after enabling redirect features.
Might be related to https://github.com/EtchUK/Etch.OrchardCore.SEO/issues/50  - i have newest version of orchard.

![image](https://user-images.githubusercontent.com/52829889/83773493-e076d700-a684-11ea-89dd-5a2526bd99b5.png)

**Comment by peterkeating** [comment]
Thanks for the heads up, will make sure when we do the RC2 updates that they play nice.

**Comment by peterkeating** [comment]
Issue here is the catch all route that the redirect feature is adding is clashing with the [catch all route being defined by the sitemaps module](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Sitemaps/Startup.cs#L218). As we can't currently define the order we end up with a clash.  Below is an open issue discussing improvements to `DynamicRouteValueTransformer` that would help get around this issue.

https://github.com/dotnet/aspnetcore/issues/21471

Will have a ponder and continue digging to see if we can find a potential work around.

**Comment by peterkeating** [comment]
@MikeKry In preparation for the pending `1.0.0` release, I've pushed up a `dev` branch that targets `1.0.0-rc2-16368` that should hopefully resolve the issue you were having. Going to close this issue but feel free to re-open if you're still having issues.
