### ISSUE TITLE
Consistent URLs

### ISSUE THREAD

**Issue by peterkeating** [EtchUK/Etch.OrchardCore.SEO#6]
Be nice to be able to specify whether URLs should be lowercase. Any URLs that aren't lowercase should be 301 redirected to the lower cased URL. We may also want to think about adding a canonical URL tag to the HTML as well.

https://www.verticalmeasures.com/blog/search-optimization/using-canonical-tag-and-redirects-solve-url-canonicalization-issues-120816/

**Comment by DannyT** [comment]
Do we have a preferred practice for trailing slashes too?
E.g.  `/about` vs `/about/`

**Comment by peterkeating** [comment]
My preference is `/about`, yours?

**Comment by DannyT** [comment]
Same but it would be nice to be configurable, I believe "Remove trailing slashes" is the setting used in Wordpress.

**Comment by peterkeating** [comment]
Agreed, being able to toggle on/off these settings would be nice. Is there anything else we should be thinking about?

**Comment by peterkeating** [comment]
Closing as we have everything we've required for client projects for a year.
