### ISSUE TITLE
How to add custom metadata tags?

### ISSUE THREAD

**Issue by devlife** [EtchUK/Etch.OrchardCore.SEO#67]
It looks like LinkedIn uses an og:image like this:

`<meta name="image" property="og:image" content="[Image URL here]">`

Is there any way to add this custom tag?

**Comment by peterkeating** [comment]
@devlife If you're using our fields module there is a dictionary field for defining custom properties. 

https://github.com/EtchUK/Etch.OrchardCore.SEO/blob/f2c092b8674e19ddd6c36d2b9a2e7a7789289761/MetaTags/Services/MetaTagsService.cs#L101

**Comment by devlife** [comment]
Ah I didn't know about the fields module. However, it doesn't allow the use of the `property` property on the meta tag. I submitted PR #69
