### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by DannyT** [EtchUK/Etch.OrchardCore.SEO#7]
We should have the option to publish a sitemap as per https://support.google.com/webmasters/answer/183668?hl=en

**Comment by peterkeating** [comment]
This will be available in the next version of Orchard Core - https://github.com/OrchardCMS/OrchardCore/pull/4450

Below is a link to a demo of the new sitemap module.

https://www.youtube.com/watch?v=fG_rFD0wffw
