### ISSUE TITLE
Redirects doesnt allow file urls

### ISSUE THREAD

**Issue by kgwadu** [EtchUK/Etch.OrchardCore.SEO#78]
When trying to add redirect rules for files e.g. /images/149947614_n.jpg i get the error _"Please do not use any of the following characters in your From URL: ":", "?", "#", "[", "]", "@", "!", "$", "&", "'", "(", ")", "*", "+", ",", ".", ";", "=", "<", ">", "\", "|", "%". No spaces are allowed (please use dashes or underscores instead)."_

Is there a reason why we can't add urls like that for a redirect?

**Comment by peterkeating** [comment]
Full stops are now accepted so this should work as of `v1.4.1`.
